name: Cqrs CI/CD

on:
    push:
        branches:
            -master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: check out code
              uses: actions/checkout@v3
            
            - name: setup .net
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0'
            
            - name: Restore dependencies
              run: dotnet-restore

            - name: Build App
              run: dotnet build -c Release --no-restore
